# Generated by Django 4.1.1 on 2022-09-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('seats', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('cpic', models.ImageField(default='', upload_to='static/course/')),
                ('sdate', models.CharField(max_length=100)),
                ('eligibility', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=200)),
            ],
        ),
    ]
