# Generated by Django 4.1.1 on 2022-09-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='hodpic',
            field=models.ImageField(default='', upload_to='static/hod/'),
        ),
    ]
