# Generated by Django 3.2.7 on 2022-09-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220909_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='vgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.TextField()),
                ('vdes', models.TextField()),
                ('vtitle', models.CharField(max_length=200)),
                ('vdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stuplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('stupic', models.ImageField(null=True, upload_to='static/profile')),
                ('designation', models.CharField(max_length=50)),
                ('pyear', models.CharField(max_length=50)),
                ('cpic', models.ImageField(upload_to='static/company')),
                ('rdate', models.DateField()),
                ('pcity', models.CharField(max_length=60)),
                ('cname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.company')),
            ],
        ),
    ]
