# Generated by Django 3.2.7 on 2022-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_stuplacement_vgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ititle', models.CharField(max_length=40)),
                ('ipic', models.ImageField(null=True, upload_to='static/infra')),
            ],
        ),
    ]
