# Generated by Django 3.2.7 on 2022-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tdetail', models.CharField(max_length=50)),
            ],
        ),
    ]
