# Generated by Django 3.2.7 on 2022-11-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20221115_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teachdetail',
        ),
    ]
